# This program says hello and ask for my name.
print('Hello World!')
print('What is your name?')
myName = input()
print('It is good to meet you, ' + myName)
print('How old are you?')
myAge = input()
print('what are your hobbies?')
Playingsports = input()
print('Are you planning on playing a sport in college?')
Yesiamonthefootballteam = input()
print('Whats are your dream jobs?')
Becomingaphysicaleducationteacher = input()